export const courses = [
  {
    id: 1,
    title: "JavaScript Mastery: From Beginner to Expert",
    image: "https://picsum.photos/200",
    instructor: "John Doe",
    rating: 2.7,
    reviewCount: 5230,
    originalPrice: 129.99,
    discountedPrice: 24.99,
    percentOff: 80,
    courseUrl: "/courses/javascript-mastery-from-beginner-to-expert",
  },
  {
    id: 2,
    title: "Python for Data Science and Machine Learning",
    image: "https://picsum.photos/200",
    instructor: "Emily Johnson",
    rating: 3.5,
    reviewCount: 6789,
    originalPrice: 119.99,
    discountedPrice: 29.99,
    percentOff: 75,
    courseUrl: "/courses/python-for-data-science-and-machine-learning",
  },
  {
    id: 3,
    title: "Full-Stack Web Development with React and Node.js",
    image: "https://picsum.photos/200",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 4320,
    originalPrice: 139.99,
    discountedPrice: 34.99,
    percentOff: 75,
    courseUrl: "/courses/full-stack-web-development-with-react-and-nodejs",
  },
  {
    id: 4,
    title: "UI/UX Design Fundamentals with Figma",
    image: "https://picsum.photos/200",
    instructor: "Sophia Davis",
    rating: 4.6,
    reviewCount: 3120,
    originalPrice: 89.99,
    discountedPrice: 17.99,
    percentOff: 80,
    courseUrl: "/courses/ui-ux-design-fundamentals-with-figma",
  },
  {
    id: 5,
    title: "The Complete Cyber Security Course",
    image: "https://picsum.photos/200",
    instructor: "Robert Wilson",
    rating: 4.9,
    reviewCount: 2890,
    originalPrice: 149.99,
    discountedPrice: 39.99,
    percentOff: 73,
    courseUrl: "/courses/the-complete-cyber-security-course",
  },
  {
    id: 6,
    title: "Digital Marketing & SEO for Beginners",
    image: "https://picsum.photos/200",
    instructor: "Jessica White",
    rating: 3.3,
    reviewCount: 5432,
    originalPrice: 79.99,
    discountedPrice: 14.99,
    percentOff: 81,
    courseUrl: "/courses/digital-marketing-and-seo-for-beginners",
  },
  {
    id: 7,
    title: "Artificial Intelligence & Deep Learning Bootcamp",
    image: "https://picsum.photos/200",
    instructor: "David Martinez",
    rating: 2.7,
    reviewCount: 4100,
    originalPrice: 199.99,
    discountedPrice: 49.99,
    percentOff: 75,
    courseUrl: "/courses/artificial-intelligence-and-deep-learning-bootcamp",
  },
];